<script>
  import { Button } from "carbon-components-svelte";
  import Download16 from "carbon-icons-svelte/lib/Download16";
</script>

<style>
  .source {
    margin-top: 0.5rem;
  }

  .source .source-logo {
    display: flex;
    padding-top: 1.5rem;
    align-items: start;
  }

  .source .source-logo img {
    width: 100px;
  }

  .source .source-text h5 {
    margin-bottom: 0.5rem;
  }

  .source .source-text p {
    margin-bottom: 0.5rem;
  }
</style>

<div class="bx--row">
  <div class="bx--col-lg-12">
    <h2>Data Sources</h2>
    <p>
      The following list of datasets were used to create this tool. Click on the
      Download Dataset buttons to download data in NetCDF, GeoTIFF or CSV
      formats. You can also download data visualized in Explore the Data section
      above in graphic and tabular formats by clicking on the Download Chart
      button.
    </p>
  </div>
</div>

<!-- Source -->
<div class="bx--row source">
  <div class="bx--col-lg-2 source-logo">
    <img src="/img/logos/scripps_100x100.png" alt="scripps logo" />
  </div>
  <div class="bx--col-lg-10 source-text">
    <h5>LOCA Downscaled Climate Projections</h5>
    <p>
      <a href="https://scripps.ucsd.edu/" target="_blank"
        >Scripps Institution Of Oceanography - University of California, San
        Diego</a
      >
    </p>
    <p>
      Daily climate projections for California at a resolution of 1/16° (about 6
      km, or 3.7 miles) generated to support climate change impact studies for
      California’s Fourth Climate Change Assessment. The data, derived from 32
      coarse-resolution (~100 km) global climate models from the CMIP5 archive,
      were bias corrected and downscaled using the Localized Constructed
      Analogues (<a href="http://loca.ucsd.edu/what-is-loca/" target="_blank"
        >LOCA</a
      >) statistical method. The data cover 1950-2005 for the historical period
      and 2006-2100 (some models stop in 2099) for two future climate
      projections. Details are described in
      <a
        href="https://www.energy.ca.gov/sites/default/files/2019-11/Projections_CCCA4-CEC-2018-006_ADA.pdf"
        target="_blank">Pierce et al., 2018</a
      >.
    </p>
    <Button size="field" kind="tertiary" icon="{Download16}" href="#!"
      >Download Dataset</Button
    >
  </div>
</div>

<!-- Source -->
<div class="bx--row source">
  <div class="bx--col-lg-2 source-logo">
    <img src="/img/logos/u_colorado.png" alt="university of colorado logo" />
  </div>
  <div class="bx--col-lg-10 source-text">
    <h5>Gridded Observed Meteorological Data</h5>
    <p>
      <a href="http://ciresgroups.colorado.edu/livneh/" target="_blank"
        >University of Colorado, Boulder</a
      >
    </p>
    <p>
      Historical observed daily temperature data from approximately 20,000 NOAA
      Cooperative Observer (COOP) stations form the basis of this gridded
      dataset from 1950–2013 at a spatial resolution of 1/16º (approximately 6
      km). Observation-based meteorological data sets offer insights into
      changes to the hydro-climatic system by diagnosing spatio-temporal
      characteristics and providing a historical baseline for future
      projections. Details are described in <a
        href="http://www.nature.com/articles/sdata201542"
        target="_blank">Livneh et al., 2015</a
      >.
    </p>
    <Button size="field" kind="tertiary" icon="{Download16}" href="#!"
      >Download Dataset</Button
    >
  </div>
</div>

<!-- Source -->
<div class="bx--row source">
  <div class="bx--col-lg-2 source-logo">
    <img
      style="width:80px;"
      src="/img/logos/gif_80x80.png"
      alt="geospatial innovation facility logo"
    />
  </div>
  <div class="bx--col-lg-10 source-text">
    <h5>Additional Calculations</h5>
    <p>
      <a href="http://gif.berkeley.edu/" target="_blank"
        >Geospatial Innovation Facility - University of California, Berkeley</a
      >
    </p>
    <p>
      In order to create data layers used in this visualization tool, we
      calculated annual averages of daily values of maximum temperature (daily
      high) minimum temperature (daily low) and precipitation for each year
      (1950–2100). This process was done for each of the 32 LOCA downscaled
      climate models for the historical scenario and the future scenarios - RCP
      4.5 and RCP 8.5.
    </p>
    <p>
      An envelope of modeled variability for each variable-scenario combination
      was generated by selecting the highest and lowest values from annual
      averages of all 32 LOCA downscaled climate models.
    </p>
    <p>
      California agencies have selected 10 of the 32 LOCA downscaled climate
      models for performance in the California/Nevada region. For more details
      on this process see <a
        href="https://www.energy.ca.gov/sites/default/files/2019-11/Projections_CCCA4-CEC-2018-006_ADA.pdf"
        target="_blank">Pierce et al., 2018</a
      >. Data for these 10 models and the gridded historical observed data are
      displayed in the tool and are available through the Cal-Adapt API.
    </p>
    <Button size="field" kind="tertiary" icon="{Download16}" href="#!"
      >Download Dataset</Button
    >
  </div>
</div>
